[ req ]
default_bits      = 4096
distinguished_name = req_distinguished_name
req_extensions    = req_extensions_section

[ req_distinguished_name ]
countryName                    = Country Name (2 letter code)
countryName_min                = 2
countryName_max                = 2
countryName_default            = UA
stateOrProvinceName            = State or Province Name (full name)
stateOrProvinceName_default    = Lviv
localityName                    = Locality Name (eg, city)
localityName_default            = Lviv
organizationName                = Organization Name (eg, company)
organizationName_default        = Test
organizationalUnitName          = Organizational Unit Name (eg, section)
organizationalUnitName_default  = IT
commonName                      = Common Name (e.g. server FQDN or YOUR name)
commonName_max                  = 64
commonName_default              = localhost
emailAddress                    = Email Address (eg, admin@example.com)
emailAddress_max                = 64
emailAddress_default            = info@test.com

[ req_extensions_section ]
subjectAltName = @subject_alternative_name_section

[ subject_alternative_name_section ]
DNS.1  = test1.ls
DNS.2  = *.test1.ls
DNS.3  = test2.ls
DNS.4  = *.test2.ls


